### ISSUE TITLE
Move functionality into promtool, move querying into separate client library.

### ISSUE THREAD

**Issue by mattkanwisher** [prometheus-junkyard/prometheus_cli#9]
So the query and queryrange functions, we reused to query the prometheus server. However we had to copy and paste them into our project cause of their package

**Comment by juliusv** [comment]
Most likely we will want to move all the command-line functionality from `prometheus_cli` into promtool (https://github.com/prometheus/prometheus/tree/master/cmd/promtool). And then perhaps it would make sense to move the underlying query functions somewhere into https://github.com/prometheus/client_golang. @fabxc - does that fit into your vision of where things should live in the future?

**Comment by fabxc** [comment]
In `client_golang` have to make a clear distinction between instrumentation library and actual client lib (the one talking to the HTTP API). I've already started the latter a few weeks back but it was put on hold:

https://github.com/prometheus/client_golang/blob/fabxc/common/client

It already contains a working implementation for the querying endpoints.
I would suggest having `client_golang/prometheus` as the instrumentation package and `client_golang/prometheus/api` as the actual client package. This way we can later extend `client_golang/alertmanager/api` and such and don't run into weird repository namings.

What we need to move the current `prometheus_cli` into `promtool` is a good querying syntax. The one of the testing language is not satisfying and the one in `prometheus_cli` isn't optimal, either. Specifying the querying times should be as easy as possible.
I had a proposal a while back, which was ditched because we didn't want to get into the business of statements and only have an expression language. But what we are doing here are statement, so we should make this part of PromQL after all.

**Comment by brian-brazil** [comment]
I'd suggest moving the HTTP API stuff into a separate repository, so that it's clear which bits the (instrumentation) client libraries are.

**Comment by fabxc** [comment]
Then we end up with a mess of client packages. For each language, for instrumentation, for API and for Alertmanager API. So that'll end up in at least 3 repositories per language.
Packages are logical units already. I see no serious source of confusion here. One package is one library.

**Comment by brian-brazil** [comment]
I'd be quite confused by what you propose, as `client_golang/prometheus/api` is unrelated to `client_golang/prometheus`. I can see people spending lots of time reading the code to figure out that they don't need the api in order to instrument.

Our first goal should be to make instrumentation easy, and we should avoid things that would turn a user away.

**Comment by fabxc** [comment]
A README dissolves that problem within 2 sentences.

**Comment by brian-brazil** [comment]
Not necessarily, we need to handle a lot of potential misconceptions and this layout only adds to them and requires more work on the part of the user to figure out how to do what they want to do.

If we're going to have the http clients for the http server apis (even wording on this is unclear, as the client does both http client and server) in the same repo it should be a separate top level directory/

**Comment by fabxc** [comment]
Fine with separate top level directory. This was an approach to not break paths. But I'm strongly against a blow up of repositories.

How about:

```
client_golang/
  prometheus/  (instrumentation lib)
  api/
    prometheus/
    alertmanager/
```

**Comment by brian-brazil** [comment]
That looks like a good approach.

**Comment by juliusv** [comment]
:+1: for not making the one seem like a logical sub-aspect of the other when they are in reality completely parallel packages.

**Comment by beorn7** [comment]
Progress tracked in https://github.com/prometheus/prometheus/issues/1605
